export { Education } from './Education';
export { Header } from './Header';
export { Languages } from './Languages';
export { Skills } from './Skills';
export { WorkExperience } from './WorkExperience';
export { Footer } from './Footer';
export { Title } from './Title';
export { Contacts } from './Contacts';
export { PersonalProjects } from './PersonalProjects';
